[package]
name = "astroimsim-uvex"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "UVEX specific code for the astroimsim ecosystem"

[dependencies]
rand = "0.10.1"
rand_distr = "0.6.0"
astroimsim-geometry = "0.1.15"
astroimsim-data = "0.1.16"
astroimsim-spectra = "0.1.10"
plotpy = "1.22.0"
rayon = "1.12.0"
serde_yaml = "0.9.34+deprecated"
serde = { version = "1.0.228", features = ["derive"] }
fitrs = "0.5.0"