#### >>>> file generated by plotpy <<<< ####

import matplotlib
matplotlib.use('Agg')
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as tck
import matplotlib.patches as pat
import matplotlib.path as pth
import matplotlib.patheffects as pff
import matplotlib.lines as lns
import matplotlib.transforms as tra
import mpl_toolkits.mplot3d
import matplotlib.tri as plt_tri
from mpl_toolkits.axes_grid1 import make_axes_locatable

# Variable to handle NaN values coming from Rust
NaN = np.nan

# List of additional objects to calculate bounding boxes
EXTRA_ARTISTS = []

# Adds an entity to the EXTRA_ARTISTS list to calculate bounding boxes
def add_to_ea(obj):
    global EXTRA_ARTISTS
    if obj!=None: EXTRA_ARTISTS.append(obj)

# Is a dictionary of mplot3d objects (one for each subplot_3d)
THREE_D = dict()

# Is a tuple holding the key to the current THREE_D object (defines the subplot_3d)
THREE_D_ACTIVE = (1,1,1)

# Creates or returns the mplot3d object with the current subplot_3d definition specified by THREE_D_ACTIVE
def ax3d():
    global THREE_D
    global THREE_D_ACTIVE
    if not THREE_D_ACTIVE in THREE_D:
        a, b, c = THREE_D_ACTIVE
        THREE_D[THREE_D_ACTIVE] = plt.gcf().add_subplot(a,b,c,projection='3d')
        THREE_D[THREE_D_ACTIVE].set_xlabel('x')
        THREE_D[THREE_D_ACTIVE].set_ylabel('y')
        THREE_D[THREE_D_ACTIVE].set_zlabel('z')
        add_to_ea(THREE_D[THREE_D_ACTIVE])
    return THREE_D[THREE_D_ACTIVE]

# Specifies the THREE_D_ACTIVE parameters to define a subplot_3d
def subplot_3d(a,b,c):
    global THREE_D_ACTIVE
    THREE_D_ACTIVE = (a,b,c)
    ax3d()

# Transforms data limits to axis limits
def data_to_axis(coords):
    plt.axis() # must call this first
    return plt.gca().transLimits.transform(coords)

# Transforms axis limits to data limits
def axis_to_data(coords):
    plt.axis() # must call this first
    return plt.gca().transLimits.inverted().transform(coords)

# Configures the aspect of axes with a same scaling from data to plot units for x, y and z.
def set_equal_axes():
    global THREE_D
    if len(THREE_D) == 0:
        ax = plt.gca()
        ax.axes.set_aspect('equal')
        return
    try:
        ax = ax3d()
        ax.set_box_aspect([1,1,1])
        limits = np.array([ax.get_xlim3d(), ax.get_ylim3d(), ax.get_zlim3d()])
        origin = np.mean(limits, axis=1)
        radius = 0.5 * np.max(np.abs(limits[:, 1] - limits[:, 0]))
        x, y, z = origin
        ax.set_xlim3d([x - radius, x + radius])
        ax.set_ylim3d([y - radius, y + radius])
        ax.set_zlim3d([z - radius, z + radius])
    except:
        import matplotlib
        print('VERSION of MATPLOTLIB = {}'.format(matplotlib.__version__))
        print('ERROR: set_box_aspect is missing in this version of Matplotlib')

# Function to ignore calls to plt such as the colorbar in an inset Axes
def ignore_this(*args, **kwargs):
    pass

################## plotting commands follow after this line ############################

xy=np.array([[0,0],[1,0],])
plt.plot(xy[:,0],xy[:,1],label=r'x axis for "basic"',color='green',linestyle='dashed',linewidth=2)
xy=np.array([[0,0],[0,1],])
plt.plot(xy[:,0],xy[:,1],label=r'y axis for "basic"',color='green',linewidth=1)
xy=np.array([[0,0],[1,0],])
plt.plot(xy[:,0],xy[:,1],label=r'x axis for "basic"',color='green',linestyle='dashed',linewidth=2)
xy=np.array([[0,0],[0,1],])
plt.plot(xy[:,0],xy[:,1],label=r'y axis for "basic"',color='green',linewidth=1)
xy=np.array([[-5,-5],[5,-5],[5,5],[-5,5],[-5,-5],])
plt.plot(xy[:,0],xy[:,1],label=r'Frame of ""',color='green',linestyle='solid',linewidth=1,markerfacecolor='green',markevery=1,markersize=10,marker='.')
t=plt.text(-4.5,-4.5,r'0',color='purple',fontsize=5)
t=plt.text(-3.5,-4.5,r'1',color='purple',fontsize=5)
t=plt.text(-2.5,-4.5,r'2',color='purple',fontsize=5)
t=plt.text(-1.5,-4.5,r'3',color='purple',fontsize=5)
t=plt.text(-0.5,-4.5,r'4',color='purple',fontsize=5)
t=plt.text(0.5,-4.5,r'5',color='purple',fontsize=5)
t=plt.text(1.5,-4.5,r'6',color='purple',fontsize=5)
t=plt.text(2.5,-4.5,r'7',color='purple',fontsize=5)
t=plt.text(3.5,-4.5,r'8',color='purple',fontsize=5)
t=plt.text(4.5,-4.5,r'9',color='purple',fontsize=5)
t=plt.text(-4.5,-3.5,r'10',color='purple',fontsize=5)
t=plt.text(-3.5,-3.5,r'11',color='purple',fontsize=5)
t=plt.text(-2.5,-3.5,r'12',color='purple',fontsize=5)
t=plt.text(-1.5,-3.5,r'13',color='purple',fontsize=5)
t=plt.text(-0.5,-3.5,r'14',color='purple',fontsize=5)
t=plt.text(0.5,-3.5,r'15',color='purple',fontsize=5)
t=plt.text(1.5,-3.5,r'16',color='purple',fontsize=5)
t=plt.text(2.5,-3.5,r'17',color='purple',fontsize=5)
t=plt.text(3.5,-3.5,r'18',color='purple',fontsize=5)
t=plt.text(4.5,-3.5,r'19',color='purple',fontsize=5)
t=plt.text(-4.5,-2.5,r'20',color='purple',fontsize=5)
t=plt.text(-3.5,-2.5,r'21',color='purple',fontsize=5)
t=plt.text(-2.5,-2.5,r'22',color='purple',fontsize=5)
t=plt.text(-1.5,-2.5,r'23',color='purple',fontsize=5)
t=plt.text(-0.5,-2.5,r'24',color='purple',fontsize=5)
t=plt.text(0.5,-2.5,r'25',color='purple',fontsize=5)
t=plt.text(1.5,-2.5,r'26',color='purple',fontsize=5)
t=plt.text(2.5,-2.5,r'27',color='purple',fontsize=5)
t=plt.text(3.5,-2.5,r'28',color='purple',fontsize=5)
t=plt.text(4.5,-2.5,r'29',color='purple',fontsize=5)
t=plt.text(-4.5,-1.5,r'30',color='purple',fontsize=5)
t=plt.text(-3.5,-1.5,r'31',color='purple',fontsize=5)
t=plt.text(-2.5,-1.5,r'32',color='purple',fontsize=5)
t=plt.text(-1.5,-1.5,r'33',color='purple',fontsize=5)
t=plt.text(-0.5,-1.5,r'34',color='purple',fontsize=5)
t=plt.text(0.5,-1.5,r'35',color='purple',fontsize=5)
t=plt.text(1.5,-1.5,r'36',color='purple',fontsize=5)
t=plt.text(2.5,-1.5,r'37',color='purple',fontsize=5)
t=plt.text(3.5,-1.5,r'38',color='purple',fontsize=5)
t=plt.text(4.5,-1.5,r'39',color='purple',fontsize=5)
t=plt.text(-4.5,-0.5,r'40',color='purple',fontsize=5)
t=plt.text(-3.5,-0.5,r'41',color='purple',fontsize=5)
t=plt.text(-2.5,-0.5,r'42',color='purple',fontsize=5)
t=plt.text(-1.5,-0.5,r'43',color='purple',fontsize=5)
t=plt.text(-0.5,-0.5,r'44',color='purple',fontsize=5)
t=plt.text(0.5,-0.5,r'45',color='purple',fontsize=5)
t=plt.text(1.5,-0.5,r'46',color='purple',fontsize=5)
t=plt.text(2.5,-0.5,r'47',color='purple',fontsize=5)
t=plt.text(3.5,-0.5,r'48',color='purple',fontsize=5)
t=plt.text(4.5,-0.5,r'49',color='purple',fontsize=5)
t=plt.text(-4.5,0.5,r'50',color='purple',fontsize=5)
t=plt.text(-3.5,0.5,r'51',color='purple',fontsize=5)
t=plt.text(-2.5,0.5,r'52',color='purple',fontsize=5)
t=plt.text(-1.5,0.5,r'53',color='purple',fontsize=5)
t=plt.text(-0.5,0.5,r'54',color='purple',fontsize=5)
t=plt.text(0.5,0.5,r'55',color='purple',fontsize=5)
t=plt.text(1.5,0.5,r'56',color='purple',fontsize=5)
t=plt.text(2.5,0.5,r'57',color='purple',fontsize=5)
t=plt.text(3.5,0.5,r'58',color='purple',fontsize=5)
t=plt.text(4.5,0.5,r'59',color='purple',fontsize=5)
t=plt.text(-4.5,1.5,r'60',color='purple',fontsize=5)
t=plt.text(-3.5,1.5,r'61',color='purple',fontsize=5)
t=plt.text(-2.5,1.5,r'62',color='purple',fontsize=5)
t=plt.text(-1.5,1.5,r'63',color='purple',fontsize=5)
t=plt.text(-0.5,1.5,r'64',color='purple',fontsize=5)
t=plt.text(0.5,1.5,r'65',color='purple',fontsize=5)
t=plt.text(1.5,1.5,r'66',color='purple',fontsize=5)
t=plt.text(2.5,1.5,r'67',color='purple',fontsize=5)
t=plt.text(3.5,1.5,r'68',color='purple',fontsize=5)
t=plt.text(4.5,1.5,r'69',color='purple',fontsize=5)
t=plt.text(-4.5,2.5,r'70',color='purple',fontsize=5)
t=plt.text(-3.5,2.5,r'71',color='purple',fontsize=5)
t=plt.text(-2.5,2.5,r'72',color='purple',fontsize=5)
t=plt.text(-1.5,2.5,r'73',color='purple',fontsize=5)
t=plt.text(-0.5,2.5,r'74',color='purple',fontsize=5)
t=plt.text(0.5,2.5,r'75',color='purple',fontsize=5)
t=plt.text(1.5,2.5,r'76',color='purple',fontsize=5)
t=plt.text(2.5,2.5,r'77',color='purple',fontsize=5)
t=plt.text(3.5,2.5,r'78',color='purple',fontsize=5)
t=plt.text(4.5,2.5,r'79',color='purple',fontsize=5)
t=plt.text(-4.5,3.5,r'80',color='purple',fontsize=5)
t=plt.text(-3.5,3.5,r'81',color='purple',fontsize=5)
t=plt.text(-2.5,3.5,r'82',color='purple',fontsize=5)
t=plt.text(-1.5,3.5,r'83',color='purple',fontsize=5)
t=plt.text(-0.5,3.5,r'84',color='purple',fontsize=5)
t=plt.text(0.5,3.5,r'85',color='purple',fontsize=5)
t=plt.text(1.5,3.5,r'86',color='purple',fontsize=5)
t=plt.text(2.5,3.5,r'87',color='purple',fontsize=5)
t=plt.text(3.5,3.5,r'88',color='purple',fontsize=5)
t=plt.text(4.5,3.5,r'89',color='purple',fontsize=5)
t=plt.text(-4.5,4.5,r'90',color='purple',fontsize=5)
t=plt.text(-3.5,4.5,r'91',color='purple',fontsize=5)
t=plt.text(-2.5,4.5,r'92',color='purple',fontsize=5)
t=plt.text(-1.5,4.5,r'93',color='purple',fontsize=5)
t=plt.text(-0.5,4.5,r'94',color='purple',fontsize=5)
t=plt.text(0.5,4.5,r'95',color='purple',fontsize=5)
t=plt.text(1.5,4.5,r'96',color='purple',fontsize=5)
t=plt.text(2.5,4.5,r'97',color='purple',fontsize=5)
t=plt.text(3.5,4.5,r'98',color='purple',fontsize=5)
t=plt.text(4.5,4.5,r'99',color='purple',fontsize=5)
xy=np.array([[-4.5,-4.5],[-3.5,-4.5],[-2.5,-4.5],[-1.5,-4.5],[-0.5,-4.5],[0.5,-4.5],[1.5,-4.5],[2.5,-4.5],[3.5,-4.5],[4.5,-4.5],[-4.5,-3.5],[-3.5,-3.5],[-2.5,-3.5],[-1.5,-3.5],[-0.5,-3.5],[0.5,-3.5],[1.5,-3.5],[2.5,-3.5],[3.5,-3.5],[4.5,-3.5],[-4.5,-2.5],[-3.5,-2.5],[-2.5,-2.5],[-1.5,-2.5],[-0.5,-2.5],[0.5,-2.5],[1.5,-2.5],[2.5,-2.5],[3.5,-2.5],[4.5,-2.5],[-4.5,-1.5],[-3.5,-1.5],[-2.5,-1.5],[-1.5,-1.5],[-0.5,-1.5],[0.5,-1.5],[1.5,-1.5],[2.5,-1.5],[3.5,-1.5],[4.5,-1.5],[-4.5,-0.5],[-3.5,-0.5],[-2.5,-0.5],[-1.5,-0.5],[-0.5,-0.5],[0.5,-0.5],[1.5,-0.5],[2.5,-0.5],[3.5,-0.5],[4.5,-0.5],[-4.5,0.5],[-3.5,0.5],[-2.5,0.5],[-1.5,0.5],[-0.5,0.5],[0.5,0.5],[1.5,0.5],[2.5,0.5],[3.5,0.5],[4.5,0.5],[-4.5,1.5],[-3.5,1.5],[-2.5,1.5],[-1.5,1.5],[-0.5,1.5],[0.5,1.5],[1.5,1.5],[2.5,1.5],[3.5,1.5],[4.5,1.5],[-4.5,2.5],[-3.5,2.5],[-2.5,2.5],[-1.5,2.5],[-0.5,2.5],[0.5,2.5],[1.5,2.5],[2.5,2.5],[3.5,2.5],[4.5,2.5],[-4.5,3.5],[-3.5,3.5],[-2.5,3.5],[-1.5,3.5],[-0.5,3.5],[0.5,3.5],[1.5,3.5],[2.5,3.5],[3.5,3.5],[4.5,3.5],[-4.5,4.5],[-3.5,4.5],[-2.5,4.5],[-1.5,4.5],[-0.5,4.5],[0.5,4.5],[1.5,4.5],[2.5,4.5],[3.5,4.5],[4.5,4.5],])
plt.plot(xy[:,0],xy[:,1],label=r'Grid points: ""',linestyle='none',markerfacecolor='blue',markevery=1,markersize=7,marker='.')
xy=np.array([[-4.5,-4.5],])
plt.plot(xy[:,0],xy[:,1],label=r'Corner: (-4.500,-4.500)',linestyle='none',markerfacecolor='#eeea83',markevery=1,markersize=10,marker='.')
plt.gcf().set_size_inches(10,10)
plt.gca().get_yaxis().set_major_locator(tck.MaxNLocator(11))
plt.gca().get_xaxis().set_major_locator(tck.MaxNLocator(11))
plt.gca().set_axisbelow(True)
plt.grid(linestyle='--',color='grey',zorder=-1000)
plt.gca().set_xlabel(r'x')
plt.gca().set_ylabel(r'y')
h,l=plt.gca().get_legend_handles_labels()
if len(h)>0 and len(l)>0:
    leg=plt.legend(handlelength=3,ncol=1,loc='best')
    add_to_ea(leg)
plt.title(r'Regular Grid on a Coordinate System')
h,l=plt.gca().get_legend_handles_labels()
if len(h)>0 and len(l)>0:
    leg=plt.legend(handlelength=3,ncol=1,loc='best')
    add_to_ea(leg)

fn=r'tests/grid1_test'
plt.savefig(fn,bbox_inches='tight',bbox_extra_artists=EXTRA_ARTISTS)
