use std::fs::{write, File};
use std::io::{BufWriter, Write};
use astroimsim_geometry::coordinate_system::{CoordinateSystem, Coordinates};
use astroimsim_geometry::grid2d::{PlotPoint, GRID2D};
use astroimsim_geometry::points::Point;
use plotpy::Plot;

pub fn generate_test_notebook() {
    let file = File::create("notebook.md").expect("Could not create notebook");
    let mut w = BufWriter::new(file);
    writeln!(w, "# Test Notebook");

    writeln!(w, "This is a notebook generated by the generate_test_notebook command in notebook.rs. In this file we will run through tests of \
    astroimsim-geometry, astroimsim-spectra, astroimsim-data, and astroimsim-uvex");


    writeln!(w, "## Tests of astroimsim-geometry");
    writeln!(w, "The astroimsim-geometry crate handles coordinate systems and regular grids on those coordinate systems. ");
    writeln!(w, "We define two coordinate systems and then plot their axis as follows:");
    writeln!(w, "```rust
    let mut plot = Plot::new();
    let grid1 = GRID2D::new_empty((10,10), (1.0,1.0), (0.0,0.0),0.001, Coordinates::RELATIVE(coords1.clone()));
    coords1.plot(&mut plot,\"green\");
    grid1.plot_outline(&mut plot,\"green\");
    grid1.plot_points(&mut plot, PlotPoint::No);
    plot.set_title(\"Regular Grid on a Coordinate System\");
    plot.legend();
    plot.save(\"tests/grid1_test\").expect(\"could not save figure\");\n```");
    let (coords1, coords2) = test_coordiantes();
    writeln!(w,"![coordiante test](tests/coordinate_test.png)");
    writeln!(w, "Now that we have coordinate systems defined, we can create regular grids with respect to these axis.");
    test_grids(coords1.clone(),coords2.clone());

    writeln!(w,"```rust \
let mut plot = Plot::new();
    let grid1 = GRID2D::new_empty((10,10), (1.0,1.0), (0.0,0.0),0.001, Coordinates::RELATIVE(coords1.clone()));
    coords1.plot(&mut plot,\"green\");
    grid1.plot_outline(&mut plot,\"green\");
    grid1.plot_points(&mut plot, PlotPoint::No);
    plot.set_title(\"Regular Grid on a Coordinate System\");
    plot.legend();
    plot.save(\"tests/grid1_test\").expect(\"could not save figure\");\n```");


    writeln!(w, "![coordiante test](tests/grid1_test.png)").expect("TODO: panic message");
    writeln!(w, "![coordiante test](tests/grid2_test.png)").expect("TODO: panic message");


    writeln!(w,"The yellow dot marks the corner, the 0th grid point. \
    In general, we may have data given on a grid and need to interpolate the data to a value which is not a grid point. To do this, we need to find the nearest neibhors of a point in the grid. \
    We visualize this by placing a point on the grid and highlighting the box it is in.");


    writeln!(w, " \
    Let us add some points now before plotting: ");


    writeln!(w, " ```rust \
    \
    let point_1 = Point::new(1.0,1.0,Coordinates::RELATIVE(coords1.clone()));
    let point_2 = Point::new(1.1,3.0,Coordinates::RELATIVE(coords1.clone()));
    let point_3 = Point::new(6.7,-2.5,Coordinates::RELATIVE(coords1.clone()));
    let point_4 = Point::new(-4.5,-2.5,Coordinates::RELATIVE(coords1.clone()));


    grid1.plot_points(&mut plot, PlotPoint::Given(point_1));
    grid1.plot_points(&mut plot, PlotPoint::Given(point_2));
    grid1.plot_points(&mut plot, PlotPoint::Given(point_3));
    grid1.plot_points(&mut plot, PlotPoint::Given(point_4));\n ```");

    test_grids_with_points(coords1,coords2);

    writeln!(w, "In the first three lines we define three points relative the the coordinate system of the grid. We can do this in the relative coordinates of both grids");

    writeln!(w,"\
    ![coordiante test](tests/grid1_points_test.png)");

    writeln!(w, "\
    ![coordiante test](tests/grid2_points_test.png)").expect("TODO: panic message");


    writeln!(w, "Trying to grid points outside of the perimeter of the grid will result in a panic. \
    However, we can project the points on the grid first. \
    This is useful for constant extensions of data given on a grid smaller than is needed. ");

    writeln!(w, " ```rust \
    \
    let point_1 = Point::new(1.0,1.0,Coordinates::RELATIVE(coords1.clone()));
    let point_2 = Point::new(1.1,3.0,Coordinates::RELATIVE(coords1.clone()));
    let point_3 = Point::new(6.7,-2.5,Coordinates::RELATIVE(coords1.clone()));
    let point_4 = Point::new(-4.5,-2.5,Coordinates::RELATIVE(coords1.clone()));


    grid1.plot_points(&mut plot, PlotPoint::Given(point_1));
    grid1.plot_points(&mut plot, PlotPoint::Given(point_2));
    grid1.plot_points(&mut plot, PlotPoint::Given(point_3));
    grid1.plot_points(&mut plot, PlotPoint::Given(point_4));\n ```");





}
pub fn test_coordiantes()-> (CoordinateSystem,CoordinateSystem){
    let mut plot = Plot::new();
    let basic_coordinates = CoordinateSystem::new((1.0,0.0),(0.0,1.0),(0.0,0.0), "basic");
    let strange_coordinates = CoordinateSystem::new((0.7,0.3),(1.4,-1.3),(0.5,0.5),"strange");
    basic_coordinates.plot(&mut plot,"green");
    strange_coordinates.plot(&mut plot, "purple");
    plot.set_title("Defining and Plotting Coordinate Systems");
    plot.legend();
    plot.save("tests/coordinate_test").expect("could not save figure");
    (basic_coordinates,strange_coordinates)

}
pub fn test_grids(coords1:CoordinateSystem,coords2:CoordinateSystem)->(GRID2D,GRID2D){


    let mut plot = Plot::new();
    let grid1 = GRID2D::new_empty((10,10), (1.0,1.0), (0.0,0.0),0.001, Coordinates::RELATIVE(coords1.clone()));
    coords1.plot(&mut plot,"green");
    grid1.plot_outline(&mut plot,"green");
    grid1.plot_points(&mut plot, PlotPoint::No);
    plot.set_title("Regular Grid on a Coordinate System");
    plot.legend();
    plot.save("tests/grid1_test").expect("could not save figure");



    let mut plot = Plot::new();
    let grid2 = GRID2D::new_empty((10,10), (1.0,1.0), (0.0,0.0),0.001, Coordinates::RELATIVE(coords2.clone()));
    coords2.plot(&mut plot, "purple");
    grid2.plot_outline(&mut plot, "purple");
    grid2.plot_points(&mut plot, PlotPoint::No);
    plot.set_title("Regular Grid on a Coordinate System");
    plot.legend();
    plot.save("tests/grid2_test").expect("could not save figure");


    (grid1,grid2)
}

pub fn test_grids_with_points(coords1:CoordinateSystem,coords2:CoordinateSystem){

    let point_1 = Point::new(1.0,1.0,Coordinates::RELATIVE(coords1.clone()));
    let point_2 = Point::new(1.1,3.0,Coordinates::RELATIVE(coords1.clone()));
    let point_3 = Point::new(2.7,-2.5,Coordinates::RELATIVE(coords1.clone()));
    let point_4 = Point::new(-4.5,-2.5,Coordinates::RELATIVE(coords1.clone()));




    let mut plot = Plot::new();
    let grid1 = GRID2D::new_empty((10,10), (1.0,1.0), (0.0,0.0),0.001, Coordinates::RELATIVE(coords1.clone()));
    coords1.plot(&mut plot,"green");
    grid1.plot_outline(&mut plot,"green");
    grid1.plot_points(&mut plot, PlotPoint::Given(point_1));
    grid1.plot_points(&mut plot, PlotPoint::Given(point_2));
    grid1.plot_points(&mut plot, PlotPoint::Given(point_3));
    grid1.plot_points(&mut plot, PlotPoint::Given(point_4));

    plot.set_title("Regular Grid on a Coordinate System");
    //plot.legend();
    plot.save("tests/grid1_points_test").expect("could not save figure");



    let mut plot = Plot::new();

    let point_1 = Point::new(1.0,1.0,Coordinates::RELATIVE(coords2.clone()));
    let point_2 = Point::new(1.1,3.0,Coordinates::RELATIVE(coords2.clone()));
    let point_3 = Point::new(2.7,-2.5,Coordinates::RELATIVE(coords2.clone()));
    let point_4 = Point::new(-4.5,-2.5,Coordinates::RELATIVE(coords2.clone()));


    let grid2 = GRID2D::new_empty((10,10), (1.0,1.0), (0.0,0.0),0.001, Coordinates::RELATIVE(coords2.clone()));
    coords2.plot(&mut plot, "purple");
    grid2.plot_outline(&mut plot, "purple");

    grid2.plot_points(&mut plot, PlotPoint::Given(point_1));
    grid2.plot_points(&mut plot, PlotPoint::Given(point_2));
    grid2.plot_points(&mut plot, PlotPoint::Given(point_3));
    grid2.plot_points(&mut plot, PlotPoint::Given(point_4));

    plot.set_title("Regular Grid on a Coordinate System");
    //plot.legend();
    plot.save("tests/grid2_points_test").expect("could not save figure");

}

pub fn test_projection(coords1:CoordinateSystem,coords2:CoordinateSystem){

    let point_1 = Point::new(6.0,1.0,Coordinates::RELATIVE(coords1.clone()));
    let point_2 = Point::new(1.1,7.0,Coordinates::RELATIVE(coords1.clone()));
    let point_3 = Point::new(-8.7,-2.5,Coordinates::RELATIVE(coords1.clone()));
    let point_4 = Point::new(-4.5,-9.5,Coordinates::RELATIVE(coords1.clone()));


    let mut plot = Plot::new();
    let grid1 = GRID2D::new_empty((10,10), (1.0,1.0), (0.0,0.0),0.001, Coordinates::RELATIVE(coords1.clone()));
    coords1.plot(&mut plot,"green");
    grid1.plot_outline(&mut plot,"green");
    grid1.plot_points(&mut plot, PlotPoint::Given(point_1));
    grid1.plot_points(&mut plot, PlotPoint::Given(point_2));
    grid1.plot_points(&mut plot, PlotPoint::Given(point_3));
    grid1.plot_points(&mut plot, PlotPoint::Given(point_4));

    plot.set_title("Regular Grid on a Coordinate System");
    //plot.legend();
    plot.save("tests/grid1_points_test").expect("could not save figure");



    let mut plot = Plot::new();

    let point_1 = Point::new(6.0,1.0,Coordinates::RELATIVE(coords2.clone()));
    let point_2 = Point::new(1.1,7.0,Coordinates::RELATIVE(coords2.clone()));
    let point_3 = Point::new(-8.7,-2.5,Coordinates::RELATIVE(coords2.clone()));
    let point_4 = Point::new(-4.5,-9.5,Coordinates::RELATIVE(coords2.clone()));



    let grid2 = GRID2D::new_empty((10,10), (1.0,1.0), (0.0,0.0),0.001, Coordinates::RELATIVE(coords2.clone()));
    coords2.plot(&mut plot, "purple");
    grid2.plot_outline(&mut plot, "purple");

    grid2.plot_points(&mut plot, PlotPoint::Given(point_1));
    grid2.plot_points(&mut plot, PlotPoint::Given(point_2));
    grid2.plot_points(&mut plot, PlotPoint::Given(point_3));
    grid2.plot_points(&mut plot, PlotPoint::Given(point_4));

    plot.set_title("Regular Grid on a Coordinate System");
    //plot.legend();
    plot.save("tests/grid2_points_test").expect("could not save figure");

}
